name: Build PBRP Recovery

on:
  workflow_dispatch:
    inputs:
      RECOVERY_NAME:
        description: 'RECOVERY_NAME'
        required: true
        default: 'PBRP'
      LIBRARY_NAME:
        description: 'LIBRARY_NAME'
        required: true
        default: 'omni'
      LIBRARY_URL:
        description: 'LIBRARY_URL'
        required: true
        default: 'https://github.com/PitchBlackRecoveryProject/manifest_pb.git'
      LIBRARY_BRANCH:
        description: 'LIBRARY_BRANCH'
        required: true
        default: 'android-9.0'
      DEVICE_URL:
        description: 'DEVICE_URL'
        required: true
        default: 'https://github.com/thongass000/android_recovery_samsung_a9y18qlte.git'
      DEVICE_BRANCH:
        description: 'DEVICE_BRANCH'
        required: true
        default: 'twrp-9.0'
      DEVICE_PATH:
        description: 'DEVICE_PATH'
        required: true
        default: 'device/samsung/a9y18qlte'
      DEVICE_NAME:
        description: 'DEVICE_NAME'
        required: true
        default: 'a9y18qlte'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-20.04

    steps:
    - name: Check Out
      uses: actions/checkout@main

    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12

    - name: Get current date
      run: |
        echo "{name}={$(date +%Y-%m-%d)}" >> $GITHUB_OUTPUT
      id: date

    - name: Prepare environment
      run: |
        export HOME=${GITHUB_WORKSPACE}
        cd ${GITHUB_WORKSPACE}
        sudo apt -y install git aria2
        git clone https://gitlab.com/OrangeFox/misc/scripts
        cd scripts
        sudo bash setup/android_build_env.sh
        sudo bash setup/install_android_sdk.sh || true

    - name: Install repo
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        export PATH=~/bin:$PATH

    - name: Initialize repo
      run: |
        PATH=~/bin:$PATH
        mkdir workspace
        cd workspace
        echo "{name}={$(pwd)}" >> $GITHUB_OUTPUT
        git config --global user.name "thongass000"
        git config --global user.email "tienthong2004@gmail.com"
        repo init --depth=1 -u ${{ github.event.inputs.LIBRARY_URL }} -b ${{ github.event.inputs.LIBRARY_BRANCH }}
      id: pwd

    - name: Repo Sync
      run: |
        PATH=~/bin:$PATH
        cd workspace
        repo sync -j$(nproc --all) -f --force-sync
        ls -al

    - name: Clone LineageOS/android_hardware_samsung
      run: |
        PATH=~/bin:$PATH
        cd ${{ steps.pwd.outputs.pwd }}
        git clone https://github.com/LineageOS/android_hardware_samsung.git -b lineage-16.0 ./hardware/samsung

    - name: Clone device
      run: |
        PATH=~/bin:$PATH
        cd ${{ steps.pwd.outputs.pwd }}
        git clone ${{ github.event.inputs.DEVICE_URL }} -b ${{ github.event.inputs.DEVICE_BRANCH }} ./${{ github.event.inputs.DEVICE_PATH }}

    - name : Patch device tree
      run: |
        cd ${{ steps.pwd.outputs.pwd }}
        cd ${{ github.event.inputs.DEVICE_PATH }}
        sed -i -e 's/vendor\/omni/vendor\/pb/g' omni_a9y18qlte.mk
        sed -i '/gsm.mk/d' omni_a9y18qlte.mk

    - name: Building
      run: |
        PATH=~/bin:$PATH
        cd ${{ steps.pwd.outputs.pwd }}
        export ALLOW_MISSING_DEPENDENCIES=true
        export LC_ALL=C
        source build/envsetup.sh
        lunch ${{ github.event.inputs.LIBRARY_NAME }}_${{ github.event.inputs.DEVICE_NAME }}-eng
        make clean
        make recoveryimage -j$(nproc --all)
        echo -e "-- Creating Odin flashable recovery tar (recovery.tar) ... "
        tar -C $outdir -H ustar -c recovery.img > $outdir/$zipname.tar
      env:
        outdir: out/target/product/${{ github.event.inputs.DEVICE_NAME }}
        zipname: $(find $outdir -name "*.zip" -exec basename \{} .zip \;)

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/recovery.img
          workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/*.tar
          workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/*.zip
        name: ${{ github.event.inputs.RECOVERY_NAME }}-${{ github.event.inputs.DEVICE_NAME }}-${{ steps.date.outputs.date }}
        tag_name: ${{ github.event.inputs.RECOVERY_NAME }}-${{ github.event.inputs.DEVICE_NAME }}-${{ steps.date.outputs.date }}
        body: ${{ github.event.inputs.RECOVERY_NAME }} recovery for ${{ github.event.inputs.DEVICE_NAME }}, built on ${{ steps.date.outputs.date }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
